- name: 포트-프로세스 점검 플레이북
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: ps-check.sh 복사
      copy:
        src: /etc/ansible/roles/scripts/ps-check.sh
        dest: /tmp/ps-check.sh
        mode: 0755

    - name: ps-check.sh 실행
      shell: bash /tmp/ps-check.sh > /tmp/ps-check-result.log
      args:
        executable: /bin/bash

    - name: 결과 수집
      fetch:
        src: /tmp/ps-check-result.log
        dest: /etc/ansible/results/
        flat: yes

